env:
  global:
    - CONAN_REFERENCE: "freetype/2.9.1"
    - CONAN_USERNAME: "appimage-conan-community"
    - CONAN_LOGIN_USERNAME: "azubieta"
    - CONAN_CHANNEL: "stable"
    - CONAN_UPLOAD: "https://api.bintray.com/conan/appimage-conan-community/public-conan"


linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
